apiVersion: v1
kind: Service
metadata:
  name: myapp1    # Name for Service
spec:
  selector:
    app: myapp1   # Select ALL PODS with Label app:myapp1
  type: NodePort
  ports:
  - port: 8080  # Service INTERNAL port
    targetPort: 8080 # POD port
    nodePort: 30000
  
