apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
spec:
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: C:\data
  capacity:
    storage: 5Gi
  claimRef:
    name: www