apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web1
  serviceName: "web1"
  template:
    metadata:
      labels:
        app: web1
    spec:
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: www
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
        